### PR TITLE
Vp66xx tcss xhci fix

### PR DESCRIPTION
**Pull request by miczyg1**

### CODE REVIEW

**Review by mkopec — APPROVED** [review]

**Comment by mkopec** [comment]
I wonder if it'll be useful on other ADL boards like NovaCustom, too

**Comment by macpijan** [comment]
@filipleple Please confirm here after testing if it fixed the problem.

**Comment by filipleple** [comment]
Solves all USB3/USB-C problems on the previously problematic unit:

`00:0d.0 USB controller: Intel Corporation Alder Lake-P Thunderbolt 4 USB Controller (rev 04)`

```
/------------------------------------------------------------------------------\
|                                One Time Boot                                 |
\------------------------------------------------------------------------------/

   Ubuntu (on SSDPR-CL100-240-G2)                        Device Path :
   SSDPR-CL100-240-G2                                    PciRoot(0x0)/Pci(0x17,
   Network Boot and Utilities                            0x0)/Sata(0x0,0xFFFF,0
   UEFI Shell                                            x0)/HD(1,GPT,40C90353-
   SanDisk Ultra                                         6D82-4EF7-BEAA-9403489
                                                         E805D,0x800,0x219800)/
                                                         \EFI\ubuntu\shimx64.ef
                                                         i







/------------------------------------------------------------------------------\
|                         F9=Reset to Defaults      F10=Save                   |
| ^v=Move Highlight       <Enter>=Select Entry      Esc=Exit                   |
| LCtrl+LAlt+F12=Save screenshot                                               |
\------------------------------------------------------------------------------/
```

**Comment by miczyg1** [comment]
> I wonder if it could be useful on other ADL boards like NovaCustom, too

Probably depends on a unit. Laptops rather do not have that issue. Also ME was particularly sluggish on VP66xx boards from what I have observed recently.

**Pull request merged**
