### PR TITLE
configs/*: update Dasharo EDK2 revision to get DasharoPayloadPkg

### PR DESCRIPTION
**Pull request by SergiiDmytruk**
Commit https://github.com/Dasharo/coreboot/commit/05adc352a59d539003b16c4bed19cf542aa941a3 pointed EDK2 revision at a commit that's not pulled by `git clone` (comes from a removed or force-pushed branch) resulting in a non-buildable EDK2 checkout.

Added detecting invalid commit hash on checkout (existing code detects only references, but not hashes).

Fixed `configs/config.protectli_vp2410` which didn't checkout edk2-platforms due to the use of wrong repo URL.

See https://github.com/Dasharo/coreboot/pull/519#issuecomment-2334483058 and https://github.com/Dasharo/coreboot/pull/519#issuecomment-2337573550.

### CODE REVIEW

**Review by krystian-hebel — APPROVED** [review]
Approved, but let's wait for CI this time.

**Comment by miczyg1** [comment]
> Commit [05adc35](https://github.com/Dasharo/coreboot/commit/05adc352a59d539003b16c4bed19cf542aa941a3) pointed EDK2 revision at incompatible version (`dasharo` branch instead of `rebased`). Fixing this.
> 
> See [#519 (comment)](https://github.com/Dasharo/coreboot/pull/519#issuecomment-2334483058) and [#519 (comment)](https://github.com/Dasharo/coreboot/pull/519#issuecomment-2337573550).

That is not entirely correct. The parent of 05adc35 is [a0727d6](https://github.com/Dasharo/edk2/commit/a0727d62b881a4de8c5a5d91cd133278da3fa49f), which belongs to rebased branch. So it was based on the rebased branch. Not sure though what was the real reason of failing...

**Comment by krystian-hebel** [comment]
> That is not entirely correct. The parent of https://github.com/Dasharo/coreboot/commit/05adc352a59d539003b16c4bed19cf542aa941a3 is [a0727d6](https://github.com/Dasharo/edk2/commit/a0727d62b881a4de8c5a5d91cd133278da3fa49f), which belongs to rebased branch.

Parent of commit on coreboot repo is a commit on edk2 repo?

**Comment by miczyg1** [comment]
> > That is not entirely correct. The parent of [05adc35](https://github.com/Dasharo/coreboot/commit/05adc352a59d539003b16c4bed19cf542aa941a3) is [a0727d6](https://github.com/Dasharo/edk2/commit/a0727d62b881a4de8c5a5d91cd133278da3fa49f), which belongs to rebased branch.
> 
> Parent of commit on coreboot repo is a commit on edk2 repo?

Oh no, of course note. I meant the parent of 433b7a3

**Comment by krystian-hebel** [comment]
> Also added `|| exit 1` to 2 `git checkout` commands so it's easier to see the error.

This seems like something worth upstreaming.

**Review by krystian-hebel — APPROVED** [review]

**Comment by SergiiDmytruk** [comment]
The new check found an issue with one of the configs (https://github.com/Dasharo/coreboot/pull/559/commits/313ef1fb56bc50632ab3c289708587d3770a35a9), hence multiple pushes.  Sent modified fix [to upstream](https://review.coreboot.org/c/coreboot/+/84292) (didn't notice existing check initially).

**Comment by SergiiDmytruk** [comment]
Ping.

**Review by krystian-hebel — APPROVED** [review]

**Pull request merged**
