### PR TITLE
novacustom fixes

### PR DESCRIPTION
**Pull request by mkopec**

### CODE REVIEW

**Comment by mkopec** [comment]
@miczyg1 can you review this one as well?

**Comment by miczyg1** [comment]
@mkopec had to remove custom params. Cherry-picked a commit that enables the perf measurement. Variable backend in SMMSTORE by default right now. Also preinstall boot options PCD is false by default.

**Comment by miczyg1** [comment]
@mkopec we also need this: https://github.com/Dasharo/coreboot/pull/412 otherwise the camera and WiFI/BT options will not appear

**Review by miczyg1 — APPROVED** [review]

**Comment by mkopec** [comment]
I guess https://github.com/Dasharo/edk2/pull/87/files needs to be merged first?

**Review by miczyg1 — DISMISSED** [review]

**Review by miczyg1 — APPROVED** [review]

**Pull request merged**
