### PR TITLE
Msi ms7d25/fan control

### PR DESCRIPTION
**Pull request by miczyg1**

### CODE REVIEW

**Comment by miczyg1** [comment]
Sample output from sensors:

```
nct6687-isa-0a20
Adapter: ISA adapter
+12V:           12.22 V  (min = +12.19 V, max = +12.22 V)
+5V:             5.06 V  (min =  +5.06 V, max =  +5.07 V)
+3.3V:           0.00 V  (min =  +0.00 V, max =  +0.00 V)
CPU Soc:         1.23 V  (min =  +0.66 V, max =  +1.23 V)
CPU Vcore:     600.00 mV (min =  +0.60 V, max =  +0.60 V)
CPU 1P8:         0.00 V  (min =  +0.00 V, max =  +0.00 V)
CPU VDDP:        0.00 V  (min =  +0.00 V, max =  +0.00 V)
DRAM:            2.50 V  (min =  +1.32 V, max =  +2.50 V)
Chipset:       898.00 mV (min =  +0.90 V, max =  +0.90 V)
CPU SA:        902.00 mV (min =  +0.90 V, max =  +0.90 V)
Voltage #2:      1.54 V  (min =  +1.53 V, max =  +1.54 V)
AVCC3:           3.34 V  (min =  +3.34 V, max =  +3.35 V)
AVSB:            0.00 V  (min =  +0.00 V, max =  +0.00 V)
VBat:            0.00 V  (min =  +0.00 V, max =  +0.00 V)
CPU Fan:       1050 RPM  (min =    0 RPM, max = 1068 RPM)
Pump Fan:         0 RPM  (min =    0 RPM, max =    0 RPM)
System Fan #1:  998 RPM  (min =  982 RPM, max = 1008 RPM)
System Fan #2:  995 RPM  (min =  990 RPM, max = 1007 RPM)
System Fan #3: 1027 RPM  (min =  998 RPM, max = 1028 RPM)
System Fan #4:    0 RPM  (min =    0 RPM, max =    0 RPM)
System Fan #5:    0 RPM  (min =    0 RPM, max =    0 RPM)
System Fan #6:  863 RPM  (min =  822 RPM, max =  863 RPM)
CPU:            +64.5°C  (low  = +31.5°C, high = +65.5°C)
System:         +37.0°C  (low  = +34.0°C, high = +37.0°C)
VRM MOS:        +31.0°C  (low  = +28.0°C, high = +31.0°C)
PCH:            +60.0°C  (low  = +52.0°C, high = +60.0°C)
CPU Socket:     +36.0°C  (low  = +29.0°C, high = +36.0°C)
PCIe x1:        +32.0°C  (low  = +31.0°C, high = +32.0°C)
M2_1:           +31.5°C  (low  = +31.5°C, high = +32.0°C)
```

Before the PR, some temperatures and voltages were not reported. CPU Fan also spinned at fixed speed above 1000RPM. When idling, the fan speed is so low, it is not even reported:

```
nct6687-isa-0a20
Adapter: ISA adapter
+12V:           12.19 V  (min = +12.19 V, max = +12.22 V)
+5V:             5.06 V  (min =  +5.06 V, max =  +5.07 V)
+3.3V:           0.00 V  (min =  +0.00 V, max =  +0.00 V)
CPU Soc:       916.00 mV (min =  +0.66 V, max =  +1.23 V)
CPU Vcore:     600.00 mV (min =  +0.60 V, max =  +0.60 V)
CPU 1P8:         0.00 V  (min =  +0.00 V, max =  +0.00 V)
CPU VDDP:        0.00 V  (min =  +0.00 V, max =  +0.00 V)
DRAM:            1.89 V  (min =  +1.32 V, max =  +2.50 V)
Chipset:       898.00 mV (min =  +0.90 V, max =  +0.90 V)
CPU SA:        898.00 mV (min =  +0.90 V, max =  +0.90 V)
Voltage #2:      1.54 V  (min =  +1.53 V, max =  +1.54 V)
AVCC3:           3.34 V  (min =  +3.34 V, max =  +3.35 V)
AVSB:            0.00 V  (min =  +0.00 V, max =  +0.00 V)
VBat:            0.00 V  (min =  +0.00 V, max =  +0.00 V)
CPU Fan:          0 RPM  (min =    0 RPM, max = 1068 RPM)
Pump Fan:         0 RPM  (min =    0 RPM, max =    0 RPM)
System Fan #1:  994 RPM  (min =  982 RPM, max = 1008 RPM)
System Fan #2: 1004 RPM  (min =  990 RPM, max = 1007 RPM)
System Fan #3: 1003 RPM  (min =  998 RPM, max = 1028 RPM)
System Fan #4:    0 RPM  (min =    0 RPM, max =    0 RPM)
System Fan #5:    0 RPM  (min =    0 RPM, max =    0 RPM)
System Fan #6:  843 RPM  (min =  822 RPM, max =  863 RPM)
CPU:            +39.5°C  (low  = +31.5°C, high = +65.5°C)
System:         +38.5°C  (low  = +34.0°C, high = +38.5°C)
VRM MOS:        +32.0°C  (low  = +28.0°C, high = +32.0°C)
PCH:            +61.0°C  (low  = +52.0°C, high = +61.0°C)
CPU Socket:     +35.5°C  (low  = +29.0°C, high = +36.0°C)
PCIe x1:        +32.0°C  (low  = +31.0°C, high = +32.0°C)
M2_1:           +32.0°C  (low  = +31.5°C, high = +32.0°C)

```

**Comment by miczyg1** [comment]
Based on NCT6686D HW datasheet and NCT6686D EC space datasheet (the former is public, the latter I got from a request issued to Nuvoton company).

**Review by mkopec — APPROVED** [review]
Very nice, I can make use of this for https://github.com/Dasharo/coreboot/pull/402 too ;)

I could not see obvious issues here, but I may have missed something.

**Comment by miczyg1** [comment]
Hmm, M900 also has NCT6686D/NCT6687D? Cool.

Note I have only tested Smart Fan IV initialization. All fan modes are implemented as per the EC space datasheet, so should be correct. However, I have not tried all possible configurations, there is plenty of the mas you can see (various tracking methods, startup_duty, manual_offset, min_duty, ambient floor, Intel DTS based control, etc.).

I am only afraid of messing up the definitions in `src/superio/nuvoton/nct6687d/nct6687d_hwm.h` or not using all of the registers somewhere...

**Pull request merged**
