### PR TITLE
Fix coreboot and Dasharo versions

### PR DESCRIPTION
**Pull request by IgorBagnucki**
Signed-off-by: Igor Bagnucki <igor.bagnucki@3mdeb.com>

### CODE REVIEW

**Review by miczyg1 — APPROVED** [review]

**Comment by miczyg1** [comment]
@IgorBagnucki you should create a release branch for the 1.0.11 version, we do not merge changes to the `protectli_vault_kbl/release` branch unless it is a whole release version branch

**Comment by IgorBagnucki** [comment]
@miczyg1 I have changed the base branch to newly created `protectli_vault_kbl/rel_v1.0.11`

**Comment by miczyg1** [comment]
@IgorBagnucki it is ging to be 1.0.12 release so should be `protectli_vault_kbl/rel_v1.0.12`

**Comment by IgorBagnucki** [comment]
@miczyg1 Sorry, PR should point to the correct branch now

**Pull request merged**
