### PR TITLE
ec/clevo/it5570: color keyboard backlight

### PR DESCRIPTION
**Pull request by mkopec**
Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>

### CODE REVIEW

**Comment by mkopec** [comment]
Looks like the backlight state isn't restored on wake, we're probably doing it too early.

**Comment by miczyg1** [comment]
Maybe putting it to https://github.com/Dasharo/coreboot/blob/504840bcd861d149bcfb66b6dafa7b4b0db60b58/src/mainboard/clevo/tgl-u/acpi/sleep.asl#L37
would be better?

**Comment by mkopec** [comment]
@miczyg1 Moving it to MS0X didn't help. Adding a `Sleep(1000)` before KBUP () doesn't help either.

**Comment by mkopec** [comment]
Superseded by https://github.com/Dasharo/coreboot/pull/136

**Pull request closed without merging**
