### PR TITLE
Vault jsl eth perf

### PR DESCRIPTION
**Pull request by macpijan**

### CODE REVIEW

**Comment by macpijan** [comment]
I is possible that we simply need to apply this to all i225 units?

**Comment by macpijan** [comment]
Test log:

```
-----------------------------------------------------------
Server listening on 5201 (test #1)
-----------------------------------------------------------
Connecting to host 10.1.1.1, port 5201
Accepted connection from 10.1.1.2, port 58888
[  5] local 10.1.1.2 port 58898 connected to 10.1.1.1 port 5201
[  5] local 10.1.1.1 port 5201 connected to 10.1.1.2 port 58898
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   296 MBytes  2.48 Gbits/sec    0    725 KBytes       
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec   295 MBytes  2.47 Gbits/sec                  
[  5]   1.00-2.00   sec   296 MBytes  2.48 Gbits/sec    0    760 KBytes       
[  5]   1.00-2.00   sec   295 MBytes  2.47 Gbits/sec                  
[  5]   2.00-3.00   sec   294 MBytes  2.47 Gbits/sec    0    760 KBytes       
[  5]   2.00-3.00   sec   294 MBytes  2.47 Gbits/sec                  
[  5]   3.00-4.00   sec   295 MBytes  2.48 Gbits/sec    0    760 KBytes       
[  5]   3.00-4.00   sec   295 MBytes  2.47 Gbits/sec                  
[  5]   4.00-5.00   sec   294 MBytes  2.47 Gbits/sec    0    760 KBytes       
[  5]   4.00-5.00   sec   295 MBytes  2.47 Gbits/sec                  
[  5]   5.00-6.00   sec   296 MBytes  2.48 Gbits/sec    0    760 KBytes       
[  5]   5.00-6.00   sec   295 MBytes  2.47 Gbits/sec                  
[  5]   6.00-7.00   sec   295 MBytes  2.48 Gbits/sec    0    760 KBytes       
[  5]   6.00-7.00   sec   295 MBytes  2.47 Gbits/sec                  
[  5]   7.00-8.00   sec   295 MBytes  2.48 Gbits/sec    0    760 KBytes       
[  5]   7.00-8.00   sec   295 MBytes  2.48 Gbits/sec                  
[  5]   8.00-9.00   sec   295 MBytes  2.47 Gbits/sec                  
[  5]   8.00-9.00   sec   296 MBytes  2.48 Gbits/sec    0   1.12 MBytes       
[  5]   9.00-10.00  sec   295 MBytes  2.47 Gbits/sec                  
[  5]  10.00-10.00  sec   640 KBytes  2.15 Gbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-10.00  sec  2.88 GBytes  2.47 Gbits/sec                  receiver
[  5]   9.00-10.00  sec   295 MBytes  2.48 Gbits/sec    0   1.12 MBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  2.88 GBytes  2.48 Gbits/sec    0             sender
[  5]   0.00-10.00  sec  2.88 GBytes  2.47 Gbits/sec                  receiver

iperf Done.
-----------------------------------------------------------
Server listening on 5201 (test #2)
-----------------------------------------------------------
iperf3: interrupt - the server has terminated
-----------------------------------------------------------
Server listening on 5201 (test #1)
-----------------------------------------------------------
Connecting to host 10.1.1.2, port 5201
Accepted connection from 10.1.1.1, port 35418
[  5] local 10.1.1.2 port 5201 connected to 10.1.1.1 port 35430
[  5] local 10.1.1.1 port 35430 connected to 10.1.1.2 port 5201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec   295 MBytes  2.47 Gbits/sec                  
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   297 MBytes  2.49 Gbits/sec    0    743 KBytes       
[  5]   1.00-2.00   sec   295 MBytes  2.47 Gbits/sec                  
[  5]   1.00-2.00   sec   294 MBytes  2.47 Gbits/sec    0    743 KBytes       
[  5]   2.00-3.00   sec   295 MBytes  2.47 Gbits/sec                  
[  5]   2.00-3.00   sec   295 MBytes  2.47 Gbits/sec    0    786 KBytes       
[  5]   3.00-4.00   sec   295 MBytes  2.47 Gbits/sec                  
[  5]   3.00-4.00   sec   295 MBytes  2.48 Gbits/sec    0    786 KBytes       
[  5]   4.00-5.00   sec   295 MBytes  2.47 Gbits/sec    0    821 KBytes       
[  5]   4.00-5.00   sec   295 MBytes  2.48 Gbits/sec                  
[  5]   5.00-6.00   sec   295 MBytes  2.48 Gbits/sec                  
[  5]   5.00-6.00   sec   296 MBytes  2.48 Gbits/sec    0    821 KBytes       
[  5]   6.00-7.00   sec   295 MBytes  2.47 Gbits/sec    0    821 KBytes       
[  5]   6.00-7.00   sec   295 MBytes  2.47 Gbits/sec                  
[  5]   7.00-8.00   sec   295 MBytes  2.47 Gbits/sec    0    821 KBytes       
[  5]   7.00-8.00   sec   295 MBytes  2.47 Gbits/sec                  
[  5]   8.00-9.00   sec   295 MBytes  2.47 Gbits/sec                  
[  5]   8.00-9.00   sec   296 MBytes  2.48 Gbits/sec    0    821 KBytes       
[  5]   9.00-10.00  sec   295 MBytes  2.47 Gbits/sec                  
[  5]  10.00-10.00  sec   896 KBytes  2.18 Gbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-10.00  sec  2.88 GBytes  2.47 Gbits/sec                  receiver
[  5]   9.00-10.00  sec   294 MBytes  2.47 Gbits/sec    0    821 KBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  2.88 GBytes  2.48 Gbits/sec    0             sender
[  5]   0.00-10.00  sec  2.88 GBytes  2.47 Gbits/sec                  receiver

```

**Comment by mkopec** [comment]
I would hope HWP would be smart enough to handle pure network load and boost accordingly, but apparently not. Whether other platforms need it probably depends on whether they can handle 2.5Gbps at base freq, so we just need to test all of them...

**Review by mkopec — APPROVED** [review]

**Comment by mkopec** [comment]
Intel has a doc with recommendations for NIC performance tuning on Linux. They directly suggest disabling power saving (ASPM, C-stateS) for IP forwarding scenarios

**Review by miczyg1 — APPROVED** [review]

**Pull request merged**
