### PR TITLE
Clevo/ns5x v1.3.0 fixes

### PR DESCRIPTION
**Pull request by mkopec**
Enable the bayhub_lv2 driver for the SD Card reader in NS5x. The laptop has a BayHubTech LV2 chip, despite the schematics saying it's a RTS5227S. Enable the correct driver so that power-saving mode can be enabled.

This fixes s0ix issues under Windows.

Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>

### CODE REVIEW

**Comment by miczyg1** [comment]
> Enable the bayhub_lv2 driver for the SD Card reader in NS5x. The laptop has a BayHubTech LV2 chip, despite the schematics saying it's a RTS5227S. Enable the correct driver so that power-saving mode can be enabled.
> 
> This fixes s0ix issues under Windows.
> 
> Signed-off-by: Michał Kopeć [michal.kopec@3mdeb.com](mailto:michal.kopec@3mdeb.com)

So, RTD3 not needed?

**Comment by mkopec** [comment]
No, RTD3 is not needed.

**Comment by miczyg1** [comment]
@mkopec what about the ps/2 keyboard?

**Comment by mkopec** [comment]
@miczyg1 added a fix for that too

**Comment by miczyg1** [comment]
@mkopec I don't see DRIVERS_PS2_KEYBOARD selected anywhere. Without it the PS/2 keyboard will not really init in coreboot

**Comment by mkopec** [comment]
Forgot to add it to defconfig. Fixed

**Review by miczyg1 — APPROVED** [review]

**Pull request merged**
