### PR TITLE
S3 for NV40MZ

### PR DESCRIPTION
**Pull request by mkopec**
Same as it was done for NS5x TGL-U.

Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>

### CODE REVIEW

**Comment by mkopec** [comment]
Updated finalize.c to match ADL implementation (implemented PMC comm natively in coreboot instead of calling FspNotify). Disabled all FSP notifications and now resume no longer hangs in FspNotify(PciEnumDone) anymore. I still get `IPC_STS.error_code 0x4` in logs but it seems to be harmless. NV40MZ completes 20 suspend/resume cycles without issue.

**Comment by mkopec** [comment]
And now after cleaning up the patches it's broken again... Needs more work.

**Comment by mkopec** [comment]
Logs suggest that coreboot jumps to the OS waking vector but nothing happens afterwards. Need to debug with a device with a debug interface, so I'm marking this as draft until we can debug this properly. Pushed some debug leftovers, too.

**Comment by miczyg1** [comment]
@mkopec is it still valid PR? I think we will go with S3/S0ix switch right?

**Comment by mkopec** [comment]
@miczyg1 We'll probably go with the switch, yes. We can close this but this branch still contains useful code like the native PMC lockdown in coreboot

**Comment by miczyg1** [comment]
@mkopec let's clean it up then (when you get some free cycles) and we can merge it to develop instead of closing

**Comment by mkopec** [comment]
Merged in https://github.com/Dasharo/coreboot/pull/419, closing.

**Pull request closed without merging**
