### PR TITLE
.github/workflows/build.yml: bring back CI

### PR DESCRIPTION
**Pull request by macpijan**
Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>

### CODE REVIEW

**Comment by miczyg1** [comment]
Looks good and it seems to work (except TGL where some bug in fan curve causes it to not build properly)

**Comment by macpijan** [comment]
@mkopec You have recently added dynamic fan curve. Is it related to that? Can you please fix that?

**Comment by macpijan** [comment]
Rebased to latest `clevo/develop`. Once build passes, I guess we can merge it.

**Comment by macpijan** [comment]
I already remember why I love github actions and why we dropped it

```
Digest: sha256:70ee1cfb5767f29ae6fb838b1aa030d7491a9779ec977d975163f237d4dc41cc
Status: Downloaded newer image for coreboot/coreboot-sdk:2021-09-23_b0d87f753c
mkdir: cannot create directory 'build': Permission denied
/bin/sh: 1: cannot create .dependencies: Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
mkdir: cannot create directory 'build': Permission denied
/bin/sh: 1: cannot create .dependencies: Permission denied
cp: cannot create regular file '.config': Permission denied
Error: Process completed with exit code 1.
```

(nothing changed in the CI config)

**Comment by macpijan** [comment]
It is not needed anymore to use differend SKDs for TGL/ADL, so adjusted the config.
Once it completes, I hope we can merge it.

**Comment by macpijan** [comment]
Since it passes and there are no more comments, I simply merged it to so it do not hang here forever.

**Pull request merged**
