### PR TITLE
Nvc heads

### PR DESCRIPTION
**Pull request by miczyg1**

### CODE REVIEW

**Comment by Scttpr** [comment]
Hi, I'm trying to follow Heads support into Dasharo coreboot to check NV41 availability with this option. Is it the right place? I do not want to be the annoying guy on social networks so I prefer to comment here, please let me know if there is a better place! Best regards :)

**Comment by macpijan** [comment]
This is correct place @Scttpr . I think we expect one more push from @miczyg1 so it boots correctly with updated / correctly published blobs.

**Comment by macpijan** [comment]
@mkopec Do we need to merge it, or is it somehow already included in the integration branch?

**Comment by miczyg1** [comment]
@macpijan yes we need to merge it.

**Comment by mkopec** [comment]
I've been testing this for a while with https://github.com/Dasharo/heads/pull/2 , merging.

**Review by mkopec — APPROVED** [review]

**Pull request merged**
