### PR TITLE
Protectli vault ehl/pop up fix

### PR DESCRIPTION
**Pull request by miczyg1**

### CODE REVIEW

**Review by mkopec — APPROVED** [review]

**Comment by pietrushnic** [comment]
@miczyg1 @mkopec, just for my information, because maybe I don't understand something. If MR/PR is approved by the reviewer, then who is responsible for merging it?

**Comment by miczyg1** [comment]
> @miczyg1 @mkopec, just for my information, because maybe I don't understand something. If MR/PR is approved by the reviewer, then who is responsible for merging it?

I guess whoever first (reviewer or author)  is going to do a local FF merge and push it.

**Comment by pietrushnic** [comment]
> > @miczyg1 @mkopec, just for my information, because maybe I don't understand something. If MR/PR is approved by the reviewer, then who is responsible for merging it?
> 
> I guess whoever first (reviewer or author) does a local FF merge and pushes it in case of the code repos, as we don't use merge button here (signatures get lost, and we want to omit merge commits done by GH)

I wonder if @mkopec knew that since he approved but did not merged for some reason.

**Comment by miczyg1** [comment]
> I wonder if @mkopec knew that since he approved but did not merged for some reason.

Doesn't really matter IMO. As long as it is approved, I am free to merge it as well. And I did it so I could finish the task, because I care. And whoever cares, should act in similar fashion. It is not only reviewer's interest to merge PRs that are approved.

**Comment by pietrushnic** [comment]
It may make sense; I just wanted to know the reasoning. I doubt this is clearly described in our processes. It is all plain logic, but for a new beginner, it may not be that obvious.

**Pull request merged**
