### PR TITLE
Odroid h4 support

### PR DESCRIPTION
**Pull request by miczyg1**

### CODE REVIEW

**Comment by miczyg1** [comment]
Everything mostly set as it should be.

The memory training isn't working yet, the platform resets somewhere inside FSP-M and loops.

@pietrushnic if you want to have some fun, feel free to build and debug :) I'm gonna set up debug FSP build...

**Comment by pietrushnic** [comment]
@miczyg1 If I only find some time, I would be glad to.

**Review by macpijan — DISMISSED** [review]
I guess it's OK to merge this. I see some build failures, but we have other failures on dasharo branch as well. Any idea what's the problem?

**Comment by miczyg1** [comment]
@macpijan I have added CI build, if it passed for ODROID board then let's merge

**Pull request merged**
