### PR TITLE
Protectli vault glk/rel 1.0.9

### PR DESCRIPTION
**Pull request by miczyg1**

### CODE REVIEW

**Comment by pietrushnic** [comment]
@miczyg1 nit: branch name should be according to documentation https://github.com/Dasharo/docs/pull/21/files#diff-3ac3e10bd217a68763b3c24ac188f46b7815db7ca2c276b862bc11d4a13164b8R9

**Comment by miczyg1** [comment]
@pietrushnic missing `v` ?

**Comment by pietrushnic** [comment]
@miczyg1 yes

**Comment by miczyg1** [comment]
Branch change: https://github.com/Dasharo/coreboot/pull/8

**Pull request closed without merging**
