### PR TITLE
Msi ms7d25/romhole smbios

### PR DESCRIPTION
**Pull request by miczyg1**
Make use of the unique SMBIOS type1 and type2 data included in the ROMHOLE.

### CODE REVIEW

**Comment by miczyg1** [comment]
All it takes is to test is to extract the ROMHOLE with meaningful info from any HCL that has a dump and inject it into Dasharo binary (injection/migration of ROMHOLE is done automatically by DTS 1.2.6 or newer, FlashBIOS button and MFlash). Sample result:

```
# dmidecode 3.3
Getting SMBIOS data from sysfs.
SMBIOS 3.3.0 present.

Handle 0x0001, DMI type 1, 27 bytes
System Information
	Manufacturer: Micro-Star International Co., Ltd.
	Product Name: MS-7E06
	Version: 1.0
	Serial Number: Default string
	UUID: 96bcfa1a-42b4-6717-a44c-d8bbc18cbea4
	Wake-up Type: Power Switch
	SKU Number: Default string
	Family: Default string

Handle 0x0002, DMI type 2, 14 bytes
Base Board Information
	Manufacturer: Micro-Star International Co., Ltd.
	Product Name: PRO Z790-P WIFI (MS-7E06)
	Version: 1.0
	Serial Number: 07D2511_LA1E346864
	Asset Tag: Not Specified
	Features:
		Board is a hosting board
		Board is replaceable
	Location In Chassis: Not Specified
	Chassis Handle: 0x0003
	Type: Motherboard
```

Of course don't pay attention to serial number indicating Z690-A on a Z790-P platform, it was just for testing.

**Comment by miczyg1** [comment]
@mkopec mind reviewing this as well?

**Comment by miczyg1** [comment]
@mkopec ping

**Comment by mkopec** [comment]
Is this romhole specific to MSI or can it be generalized to more boards? Is it related to AMI Romhole found in some AMI dumps?

**Comment by miczyg1** [comment]
> Is this romhole specific to MSI or can it be generalized to more boards? Is it related to AMI Romhole found in some AMI images?

MSI ROMHOLE is probably based on AMI ROMHOLE, but only to the extent of flash space reservation. The layout of information stored is specific to MSI. It can be generalized to more MSI boards for sure. As you may have noticed, it can be generalized by passing the parameters as input to the ROMHOLE generation tool:
https://github.com/Dasharo/coreboot/blob/msi_ms7d25/release/util/msi/romholetool/romholetool.c#L16

It could probably use some Kconfig to be more generic and the utility could take these as input parameters... However, without more MSI boards ported, there is no need for it yet.

@mkopec

**Review by mkopec — APPROVED** [review]
Indeed, ASUS's romhole does not share  many similarities. If another MSI board in coreboot needs to use this, it'll probably be good to move it to common code. For now this is fine I think.

**Pull request merged**
