### PR TITLE
src/mb/clevo: Avoid conflict of VBNV offset and ramtop in CMOS

### PR DESCRIPTION
**Pull request by miczyg1**
Should fix: https://github.com/Dasharo/dasharo-issues/issues/556

However, I could not reproduce the popup after the upgrade. But most likely this is the culprit.

### CODE REVIEW

**Comment by mkopec** [comment]
@miczyg1 the checksum ranges also need to be updated, right?

**Comment by macpijan** [comment]
I rebased to enable CI

**Comment by miczyg1** [comment]
> @miczyg1 the checksum ranges also need to be updated, right?

I don't see a need

**Comment by mkopec** [comment]
@miczyg1 

> I don't see a need

The vbnv must be outside of the checksummed range, otherwise coreboot may reset it, which can render to bootloop in the recovery path

https://github.com/Dasharo/coreboot/pull/251
https://github.com/Dasharo/dasharo-issues/issues/242

**Pull request merged**
