### PR TITLE
configs/config.protectli_vp2420: Disable HECI at pre-boot

### PR DESCRIPTION
**Pull request by miczyg1**

### CODE REVIEW

**Comment by macpijan** [comment]
@miczyg1 Do you have some logs from testing this, or it needs testing?

**Comment by miczyg1** [comment]
Needs testing still, platform was occupied by someone (osfv_robot_

**Comment by miczyg1** [comment]
MES001.001 test PASS

**Comment by miczyg1** [comment]
@macpijan ping

**Review by mkopec — DISMISSED** [review]

**Pull request merged**
