### PR TITLE
configs/novacustom_*_adl*: bump edk2 rev to include boot menu disable

### PR DESCRIPTION
**Pull request by mkopec**

### CODE REVIEW

**Comment by miczyg1** [comment]
I am bumping to even higher revision in my PR which enables S3/S0ix runtime switch. Plus I have got fixes for that boot menu registering which didn't work well at all

**Comment by macpijan** [comment]
@mkopec Can we rebase on top of the current develop, so CI can be triggered?

**Comment by mkopec** [comment]
Rebased and retargeted

**Comment by mkopec** [comment]
Superseded by commit https://github.com/Dasharo/coreboot/commit/d0c4370562277e97ebb1159bb4a4d330e5ffedda

**Pull request closed without merging**
