### PR TITLE
Novacustom nv4x adl/rel v1.7.0

### PR DESCRIPTION
**Pull request by mkopec**

### CODE REVIEW

**Comment by mkopec** [comment]
Still need to add CI. Would be nice to integrate debug builds into CI using the Kconfig fragments added here.

**Comment by mkopec** [comment]
I think this is ready for review now.

**Comment by mkopec** [comment]
Alright, let's wait for one more edk2 change before testing.

**Comment by macpijan** [comment]
@mkopec @miczyg1 So these two should still go in first?
- [ ] https://github.com/Dasharo/edk2/pull/82
- [ ] https://github.com/Dasharo/edk2/pull/75

**Review by macpijan — COMMENTED** [review]
Feature-wise, I think we have all that we needed here already

**Comment by mkopec** [comment]
@macpijan yes, both.

**Comment by mkopec** [comment]
@macpijan merged both and bumped up edk2 rev here. Let's wait for CI to pass and these bins will be good for testing, I believe.

**Comment by mkopec** [comment]
@miczyg1 @macpijan All builds passed with no errors. Can we proceed with this PR?

**Review by macpijan — APPROVED** [review]

**Comment by macpijan** [comment]
approved @mkopec

**Pull request merged**
