### PR TITLE
Clevo/backlight fix

### PR DESCRIPTION
**Pull request by miczyg1**
This PR changes the following:

1. Reverts to old vboot branch from Dasharo fork.
2. Updates the vboot submodule pointer to the pop-up fix backported from upstream gerrit.
3. Enables keyboard backlight restoration on boot in coreboot for better UX.
4. Fixes Windows 11 reboot backlight not being restored.

### CODE REVIEW

**Review by krystian-hebel — COMMENTED** [review]
How is vboot related to backlight?

**Comment by miczyg1** [comment]
> How is vboot related to backlight?

Not related, but I got boot loops with newer vboot so had to revert it back to the older revision. It seems coreboot base is too old for upstream vboot

**Comment by krystian-hebel** [comment]
And it wasn't caught in previous release?

**Comment by miczyg1** [comment]
> And it wasn't caught in previous release?

It wasn't yet available in previous release AFAIK

**Review by krystian-hebel — APPROVED** [review]

**Comment by krystian-hebel** [comment]
@miczyg1 please rebase, this doesn't apply cleanly.

**Comment by miczyg1** [comment]
@krystian-hebel rebased locally and fast-forwarded to clevo/develop. However GH did not detect the PR being merged, so closing.

**Pull request closed without merging**
