### PR TITLE
mb/msi/ms7d5: add GPIO macros

### PR DESCRIPTION
**Pull request by mkopec**
Based on the output of [inteltool](https://review.coreboot.org/c/coreboot/+/63374)  and [intelp2m](https://review.coreboot.org/c/coreboot/+/63403)

Signed-off-by: Michał Kopeć <michal.kopec@3mdeb.com>

### CODE REVIEW

**Comment by mkopec** [comment]
Currently, this will not build due to missing GPIO definitions for ADL-H.

**Comment by miczyg1** [comment]
Please rebase. And why still a draft? I something missing here?

**Comment by mkopec** [comment]
@miczyg1 Please see comment above. Doesn't build at the moment, since the GPIO definitions for ADL PCH-H are missing in coreboot.

**Comment by miczyg1** [comment]
Then we have to add that.

**Comment by mkopec** [comment]
Rebased

**Comment by mkopec** [comment]
Added GPIO defs. Still need to wire them up

**Comment by mkopec** [comment]
Pushed upstream: https://review.coreboot.org/c/coreboot/+/63490/2

Closing this PR.

**Pull request closed without merging**
